steps:
  # build and push the container image
 - name: "gcr.io/kaniko-project/executor:latest" 
   args: ["--cache=true", "--cache-ttl=48h", "--destination=grc.io/$PROJECT_ID/marmalade-frambu:latest"]
  # Deploy container image to cloud run
  name: "gcr.io/cloud-builders/gcloud"
  args: "beta", "run", "deploy", "marmalade-frambu", "--image", "gcr.io/$PROJECT_ID/marmalade-frambu:latest", "--region", "us-central1", "--allow-unauthenticated", "--platform", "managed"]
